export const anatOptions = [
  { value: "right lung", label: "right lung" },
  { value: "right apical zone", label: "right apical zone" },
  { value: "right upper lung zone", label: "right upper lung zone" },
  { value: "right mid lung zone", label: "right mid lung zone" },
  { value: "right lower lung zone", label: "right lower lung zone" },
  { value: "right hilar structures", label: "right hilar structures" },
  { value: "right costophrenic angle", label: "right costophrenic angle" },
  { value: "left lung", label: "left lung" },
  { value: "left apical zone", label: "left apical zone" },
  { value: "left upper lung zone", label: "left upper lung zone" },
  { value: "left mid lung zone", label: "left mid lung zone" },
  { value: "left lower lung zone", label: "left lower lung zone" },
  { value: "left hilar structures", label: "left hilar structures" },
  { value: "left costophrenic angle", label: "left costophrenic angle" },
  { value: "mediastinum", label: "mediastinum" },
  { value: "upper mediastinum", label: "upper mediastinum" },
  { value: "cardiac silhouette", label: "cardiac silhouette" },
  { value: "trachea", label: "trachea" },
  { value: "right hemidiaphragm", label: "right hemidiaphragm" },
  { value: "left hemidiaphragm", label: "left hemidiaphragm" },
  { value: "right clavicle", label: "right clavicle" },
  { value: "left clavicle", label: "left clavicle" },
  { value: "spine", label: "spine" },
  { value: "right atrium", label: "right atrium" },
  { value: "cavoatrial junction", label: "cavoatrial junction" },
  { value: "svc", label: "svc" },
  { value: "aortic arch", label: "aortic arch" },
  { value: "abdomen", label: "abdomen" },
  { value: "right chest wall", label: "right chest wall" },
  { value: "left chest wall", label: "left chest wall" },
  { value: "right shoulder", label: "right shoulder" },
  { value: "left shoulder", label: "left shoulder" },
  { value: "neck", label: "neck" },
  { value: "right arm", label: "right arm" },
  { value: "left arm", label: "left arm" },
  { value: "right breast", label: "right breast" },
  { value: "left breast", label: "left breast" },
];

export const attrOptions = [
  { value: "lung opacity", label: "lung opacity" },
  { value: "consolidation", label: "consolidation" },
  { value: "pleural effusion", label: "pleural effusion" },
  {
    value: "pulmonary edema/hazy opacity",
    label: "pulmonary edema/hazy opacity",
  },
  { value: "atelectasis", label: "atelectasis" },
  { value: "pneumonia", label: "pneumonia" },
  {
    value: "enlarged cardiac silhouette",
    label: "enlarged cardiac silhouette",
  },
  { value: "pneumothorax", label: "pneumothorax" },
  {
    value: "fluid overload/heart failure",
    label: "fluid overload/heart failure",
  },
];

export const compOptions = [
  { value: "no change", label: "no change" },
  { value: "worsened", label: "worsened" },
  { value: "improved", label: "improved" },
];
